const actionTypes = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  GET_PAST_COMPETITION: 'GET_PAST_COMPETITION',
  GET_PAST_COMPETITION_SUCCESS: 'GET_PAST_COMPETITION_SUCCESS',
  GET_PAST_COMPETITION_FAILURE: 'GET_PAST_COMPETITION_FAILURE',

  GET_ONGOING_COMPETITION: 'GET_ONGOING_COMPETITION',
  GET_ONGOING_COMPETITION_SUCCESS: 'GET_ONGOING_COMPETITION_SUCCESS',
  GET_ONGOING_COMPETITION_FAILURE: 'GET_ONGOING_COMPETITION_FAILURE',

  GET_UPCOMING_COMPETITION: 'GET_UPCOMING_COMPETITION',
  GET_UPCOMING_COMPETITION_SUCCESS: 'GET_UPCOMING_COMPETITION_SUCCESS',
  GET_UPCOMING_COMPETITION_FAILURE: 'GET_UPCOMING_COMPETITION_FAILURE',

  GET_CLOSED_COMPETITION: 'GET_CLOSED_COMPETITION',
  GET_CLOSED_COMPETITION_SUCCESS: 'GET_CLOSED_COMPETITION_SUCCESS',
  GET_CLOSED_COMPETITION_FAILURE: 'GET_CLOSED_COMPETITION_FAILURE',

  ADD_STUDENT_COMPETITION: 'ADD_STUDENT_COMPETITION',
  ADD_STUDENT_COMPETITION_SUCCESS: 'ADD_STUDENT_COMPETITION_SUCCESS',
  ADD_STUDENT_COMPETITION_FAILURE: 'ADD_STUDENT_COMPETITION_FAILURE',

  UPDATE_STUDENT_COMPETITION: 'UPDATE_STUDENT_COMPETITION',
  UPDATE_STUDENT_COMPETITION_SUCCESS: 'UPDATE_STUDENT_COMPETITION_SUCCESS',
  UPDATE_STUDENT_COMPETITION_FAILURE: 'UPDATE_STUDENT_COMPETITION_FAILURE',

  GET_STUDENT_COMPETITION_MASTER_DETAILS: 'GET_STUDENT_COMPETITION_MASTER_DETAILS',
  GET_STUDENT_COMPETITION_MASTER_DETAILS_SUCCESS: 'GET_STUDENT_COMPETITION_MASTER_DETAILS_SUCCESS',
  GET_STUDENT_COMPETITION_MASTER_DETAILS_FAILURE: 'GET_STUDENT_COMPETITION_MASTER_DETAILS_FAILURE',

  GET_STUDENT_COMPETITION_DETAILS: 'GET_STUDENT_COMPETITION_DETAILS',
  GET_STUDENT_COMPETITION_DETAILS_SUCCESS: 'GET_STUDENT_COMPETITION_DETAILS_SUCCESS',
  GET_STUDENT_COMPETITION_DETAILS_FAILURE: 'GET_STUDENT_COMPETITION_DETAILS_FAILURE',
  CLEAR_STUDENT_COMPETITION_DETAILS: 'CLEAR_STUDENT_COMPETITION_DETAILS',

  CREATE_COMPETITION: 'CREATE_COMPETITION',
  CREATE_COMPETITION_SUCCESS: 'CREATE_COMPETITION_SUCCESS',
  CREATE_COMPETITION_FAILURE: 'CREATE_COMPETITION_FAILURE',

  END_COMPETITION: 'END_COMPETITION',
  END_COMPETITION_SUCCESS: 'END_COMPETITION_SUCCESS',
  END_COMPETITION_FAILURE: 'END_COMPETITION_FAILURE',

  GET_ALL_STUDENTS: 'GET_ALL_STUDENTS',
  GET_ALL_STUDENTS_SUCCESS: 'GET_ALL_STUDENTS_SUCCESS',
  GET_ALL_STUDENTS_FAILURE: 'GET_ALL_STUDENTS_FAILURE',

  ADD_STUDENT: 'ADD_STUDENT',
  ADD_STUDENT_SUCCESS: 'ADD_STUDENT_SUCCESS',
  ADD_STUDENT_FAILURE: 'ADD_STUDENT_FAILURE',

  GET_USER_PROFILE: 'GET_USER_PROFILE',
  GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
  GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_FAILURE',

  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',
};

export default actionTypes;
